services:
  nginx-proxy-manager:
    container_name: ${CONTAINER_PREFIX}nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    restart: ${RESTART_POLICY}
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    volumes:
      - ${CONFIG_PATH}/nginx-proxy-manager/data:/data
      - ${CONFIG_PATH}/nginx-proxy-managerletsencrypt:/etc/letsencrypt
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 64M
