services:
  nginx-proxy-manager:
    container_name: ${CONTAINER_PREFIX}nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: ${RESTART_POLICY}
    ports:
      # These ports are in format <host-port>:<container-port>
      - '8081:80' # Public HTTP Port
      - '4443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ${CONFIG_PATH}/nginx-proxy-manager/data:/data
      - ${CONFIG_PATH}/nginx-proxy-managerletsencrypt:/etc/letsencrypt
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    cpu_shares: 512