services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: ${CONTAINER_PREFIX}duplicati
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_PASS}
    volumes:
      - ${CONFIG_PATH}/duplicati/config:/config
      - ${CONFIG_PATH}/duplicati/backups:/backups
      - /:/source
    ports:
      - 8200:8200
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 400M
        reservations:
          cpus: "0.1"
          memory: 128M
    cpu_shares: 512
