services:
  n8n:
    image: n8nio/n8n:latest
    container_name: ${CONTAINER_PREFIX}n8n
    restart: ${RESTART_POLICY}
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_RUNNERS_ENABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
    volumes:
      - ${CONFIG_PATH}/n8n_data:/home/node/.n8n
      - ${CONFIG_PATH}/n8n_data/local-files:/files
