services:
  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: ${CONTAINER_PREFIX}radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${SSD_PATH}/movies:/data/movies
      - ${SSD_PATH}/downloads:/data/downloads
    ports:
      - 7878:7878
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 400M
        reservations:
          cpus: "0.1"
          memory: 128M
    cpu_shares: 512
