services:
  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: ${CONTAINER_PREFIX}radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${SSD_PATH}/movies:/data/movies
      - ${SSD_PATH}/downloads:/data/downloads
    ports:
      - 7878:7878
    restart: ${RESTART_POLICY}

