services:
  jackett:
    image: ghcr.io/hotio/jackett:latest
    container_name: ${CONTAINER_PREFIX}jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_PATH}/jackett:/config
      - ${SSD_PATH}/downloads:/data/downloads
    ports:
      - 9117:9117
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          memory: 512M
          memory: 128M
