services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: ${CONTAINER_PREFIX}filebrowser
    volumes:
      - /home:/srv/home
      - /DATA:/srv/DATA
      - /mnt/exdisk:/srv/exdisk
      - ${CONFIG_PATH}/filebrowser:/database
      - ${CONFIG_PATH}/filebrowser:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8001:80
    restart: ${RESTART_POLICY}

