services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: ${CONTAINER_PREFIX}filebrowser
    volumes:
      - /:/data
      - /mnt/exdisk:/kingston
      - ${CONFIG_PATH}/filebrowser/filebrowser.db:/config/database.db
      - ${CONFIG_PATH}/filebrowser/settings.json:/config/settings.json
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8001:80
    restart: ${RESTART_POLICY}