services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: ${CONTAINER_PREFIX}filebrowser
    volumes:
      - /home:/srv/home
      - /mnt/exdisk:/srv/exdisk
      - ${CONFIG_PATH}/filebrowser:/database
      - ${CONFIG_PATH}/filebrowser:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8001:80
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 200M
        reservations:
          cpus: "0.05"
          memory: 64M
    cpu_shares: 256
