services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: ${CONTAINER_PREFIX}filebrowser
    volumes:
      - /:/data
      - /mnt/exdisk:/kingston
      - ${CONFIG_PATH}/filebrowser/filebrowser.db:/database.db
      - ${CONFIG_PATH}/filebrowser/.filebrowser.json:/.filebrowser.json
    ports:
      - 8001:80
    restart: ${RESTART_POLICY}