services:
  redlib:
    image: quay.io/redlib/redlib:latest
    restart: ${RESTART_POLICY}
    container_name: "redlib"
    ports:
      - 9095:8080 
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
      # - seccomp=seccomp-redlib.json
    cap_drop:
      - ALL
    networks:
      - redlib
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s

networks:
  redlib: