services:

  # Emby: A powerful media server that organizes and streams your video, music, live TV, and photos from personal media libraries to smart TVs, streaming boxes, and mobile devices. Features a standalone server with comprehensive media management capabilities.
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: ${CONTAINER_PREFIX}emby
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/emby:/config
      - ${SSD_PATH}/tv:/data/tvshows
      - ${SSD_PATH}/movies:/data/movies
    ports:
      - 8096:8096
    restart: ${RESTART_POLICY}