services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: ${CONTAINER_PREFIX}emby
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/emby:/config
      - ${SSD_PATH}/tv:/data/tvshows
      - ${SSD_PATH}/movies:/data/movies
    ports:
      - 8096:8096
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1500M
        reservations:
          cpus: "0.5"
          memory: 256M
    cpu_shares: 1024
