services:
  dash:
    image: mauricenino/dashdot:latest
    container_name: ${CONTAINER_PREFIX}dash
    restart: ${RESTART_POLICY}
    privileged: true
    ports:
      - '5059:3001'
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_WIDGET_LIST: 'os,cpu,storage,ram,network,gpu'
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    cpu_shares: 384