networks:
  gitea:
    external: false

services:
  server:
    image: docker.gitea.com/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__SSH_PORT=2221
    restart: ${RESTART_POLICY}
    networks:
      - gitea
    volumes:
      - ${CONFIG_PATH}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2221:22"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 400M
        reservations:
          cpus: "0.1"
          memory: 128M
    cpu_shares: 512
