services:
  purgarr:
    image: ghcr.io/steveharsant/purgarr:latest
    container_name: ${CONTAINER_PREFIX}purgarr
    environment:
      - QBIT_URL='http://192.168.1.3:8080'
      - QBIT_USER='admin-qbittorrent'
      - QBIT_PASSWORD=${QBIT_PASS}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - SONARR_URL='http://192.168.1.3:8989'
      - RADARR_API_KEY=${RADARR_API_KEY}
      - RADARR_URL='http://192.168.1.3:7878'
    ports:
      - 9891:9891
    restart: ${RESTART_POLICY}