services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${CONTAINER_PREFIX}portainer
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}/portainer:/data
    environment:
      - TZ=${TZ}
    restart: ${RESTART_POLICY}

