services:

  # Jellyseerr: A request management and media discovery tool for Jellyfin. Fork of Overseerr with native Jellyfin support.
  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:latest
    container_name: ${CONTAINER_PREFIX}jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/config
    ports:
      - 5055:5055
    dns:
      - 1.1.1.1               
    network_mode: bridge
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: '0.6'         # Increased CPU limit
          memory: 768M        # Increased memory limit
        reservations:
          cpus: '0.3'         # Higher CPU reservation
          memory: 384M        # Higher memory reservation
    cpu_shares: 768          # Increased priority
