services:
  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:latest
    container_name: ${CONTAINER_PREFIX}jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/config
    ports:
      - 5055:5055
    dns:
      - 9.9.9.9
    network_mode: bridge
    restart: ${RESTART_POLICY}

