services:
  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:latest
    container_name: ${CONTAINER_PREFIX}jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/config
    ports:
      - 5055:5055
    dns:
      - 9.9.9.9
    network_mode: bridge
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 400M
        reservations:
          cpus: "0.1"
          memory: 128M
    cpu_shares: 512
