services:
  suggestarr:
    image: ciuse99/suggestarr:latest
    container_name: SuggestArr
    restart: ${RESTART_POLICY}
    ports:
      - 5001:5000
    volumes:
      - ${CONFIG_PATH}/suggestarr/config_files:/app/config/config_files
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 64M
