services:

  # Sonarr: Smart PVR for usenet and bittorrent users. Monitors multiple RSS feeds for new TV show episodes, automatically grabbing, sorting, and renaming them.
  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: ${CONTAINER_PREFIX}sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${SSD_PATH}/tv:/data/tv
      - ${SSD_PATH}/downloads:/data/downloads
    ports:
      - 8989:8989
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    cpu_shares: 512
