services:
  glance:
    container_name: ${CONTAINER_PREFIX}glance
    image: glanceapp/glance
    restart: ${RESTART_POLICY}
    privileged: true
    volumes:
      - ${CONFIG_PATH}/glance/config:/app/config
      - ${CONFIG_PATH}/glance/assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/exdisk:/mnt/exdisk
    ports:
      - 8085:8080
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 200M
        reservations:
          cpus: "0.05"
          memory: 64M
    cpu_shares: 256
