services:
  watchtower:
    image: containrrr/watchtower
    container_name: ${CONTAINER_PREFIX}watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --debug