services:
  watchtower:
    image: containrrr/watchtower
    container_name: ${CONTAINER_PREFIX}watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --cleanup --debug
    restart: ${RESTART_POLICY}
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=discord://${TOKEN}@${WEBHOOKID}
      - WATCHTOWER_NOTIFICATION_TEMPLATE="({{.Level}})':'{{.Message}}{{println}}{{end}}"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M
    cpu_shares: 128