services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: ${CONTAINER_PREFIX}watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      # --cleanup: Removes old images after updating containers.
      # --debug: Enables debug logging for more verbose output.
      # --schedule "0 0 * * 0": Runs every Sunday at midnight (00:00).
      --cleanup --debug --schedule "0 0 * * 0"