services:
    watchstate:
        image: ghcr.io/arabcoders/watchstate:latest
        # To change the user/group id associated with the tool change the following line.
        user: "0:0"
        container_name: ${CONTAINER_PREFIX}watchstate
        restart: ${RESTART_POLICY}
        ports:
            - "8002:8080" # The port which the webui will be available on.
        volumes:
            - ${CONFIG_PATH}/watchstate:/config:rw # mount current directory to container /config directory.
        deploy:
            resources:
                limits:
                    cpus: '0.3'
                    memory: 384M
                reservations:
                    cpus: '0.15'
                    memory: 192M
        cpu_shares: 512