services:
  watchstate:
    image: ghcr.io/arabcoders/watchstate:latest
    user: "0:0"
    container_name: ${CONTAINER_PREFIX}watchstate
    ports:
      - "8002:8080"
    volumes:
      - ${CONFIG_PATH}/watchstate:/config:rw
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
