services:
  cloudflared:
    container_name: ${CONTAINER_PREFIX}cloudflared-web
    image: ghcr.io/wisdomsky/cloudflared-web:latest
    environment:
      WEBUI_PORT: 1111
    volumes:
      - ${CONFIG_PATH}/cloudflared/config:/config
    restart: ${RESTART_POLICY}
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 128M
