services:
  cloudflared:
    container_name: ${CONTAINER_PREFIX}cloudflared-web
    image: ghcr.io/wisdomsky/cloudflared-web:latest
    environment:
      WEBUI_PORT: 1111
    volumes:
      - ${CONFIG_PATH}/cloudflared/config:/config
    restart: ${RESTART_POLICY}
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 200M
        reservations:
          cpus: "0.05"
          memory: 64M
    cpu_shares: 256
