services:

  # AdGuard Home: Network-wide ads & trackers blocking DNS server.
  adguardhome:
    container_name: ${CONTAINER_PREFIX}adguardhome
    image: adguard/adguardhome:v0.107.62
    ports:
      - "8089:80/tcp"
      - "90443:443/tcp"
      - "90443:443/udp"
      - "53:53/udp"
      - "53:53/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "3000:3000/tcp"
    volumes:
      - ${CONFIG_PATH}/adguardhome/conf:/opt/adguardhome/conf
      - ${CONFIG_PATH}/adguardhome/work:/opt/adguardhome/work
    environment:
      - TZ=${TZ}
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 384M
        reservations:
          cpus: '0.2'
          memory: 256M
    cpu_shares: 512