services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ${CONFIG_PATH}/uptime-kuma-data:/app/data
    ports:
      - 3001:3001
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 64M
