services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: ${CONTAINER_PREFIX}qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${SSD_PATH}/downloads:/data/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
