services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: ${CONTAINER_PREFIX}qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${SSD_PATH}/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: ${RESTART_POLICY}
