services:
  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot
    restart: ${RESTART_POLICY}
    volumes:
      - ${CONFIG_PATH}/redbot:/data
    environment:
      - TOKEN=${DISCORD_TOKEN}
      - PREFIX=.
      - TZ=Europe/Bucharest
      - PUID=1000
    mem_limit: 384m
    cpus: 0.3