services:
  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot
    restart: ${RESTART_POLICY}
    volumes:
      - ${CONFIG_PATH}/redbot:/data
    environment:
      - TOKEN=${DISCORD_TOKEN}
      - PREFIX=.
      - TZ=Europe/Bucharest
      - PUID=1000
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 200M
        reservations:
          cpus: "0.05"
          memory: 64M
    cpu_shares: 256
