services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/nextcloud/config:/config
      - ${SSD_PATH}/nextcloud:/data
    ports:
      - 4443:443
    restart: ${RESTART_POLICY}